"""empty message

Revision ID: 22cfeb3fc4cb
Revises: dd9a259ff87b
Create Date: 2025-03-19 19:05:28.889034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cfeb3fc4cb'
down_revision: Union[str, None] = 'dd9a259ff87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
