"""empty message

Revision ID: dd78ac333a2e
Revises: 22cfeb3fc4cb
Create Date: 2025-03-19 19:05:42.149692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd78ac333a2e'
down_revision: Union[str, None] = '22cfeb3fc4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participates', sa.Column('giveaway_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participates', 'giveaway_id')
    # ### end Alembic commands ###
