"""empty message

Revision ID: dd9a259ff87b
Revises: c04ce2d37a46
Create Date: 2025-03-19 19:05:07.448711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9a259ff87b'
down_revision: Union[str, None] = 'c04ce2d37a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participates', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participates', sa.Column('chat_id', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###
